project:
  type: website
  pre-render: copy_readme.R
filters:
- newpagelink.lua
format:
  html:
    theme: morph
    css: styles.css
    toc: true
    code-copy: true
language:
  search-text-placeholder: Search (press "s")
execute:
  eval: false
website:
  title: jarl
  repo-url: https://github.com/etiennebacher/jarl
  repo-subdir: docs
  repo-actions:
  - source
  - issue
  search:
    location: navbar
    type: textbox
    keyboard-shortcut: s
  navbar:
    right:
    - icon: github
      href: https://github.com/etiennebacher/jarl
      aria-label: GitHub
    left:
    - text: Using Jarl
      href: using-jarl.md
    - text: Configuration
      href: config.md
    - text: Rules
      href: rules.qmd
    - text: Editors
      href: editors.md
    - text: Integrations
      href: integrations.md
    - text: Contributing
      menu:
      - text: General information
        href: contributing.md
      - text: 'Tutorial: add a new rule'
        href: contributing-rule-example.md
    - text: Changelog
      href: changelog.md
  sidebar:
  - title: Rules
    style: floating
    contents:
    - rules.qmd
    - section: List of rules
      contents:
      - rules/all_equal.md
      - rules/any_duplicated.md
      - rules/any_is_na.md
      - rules/assignment.md
      - rules/browser.md
      - rules/class_equals.md
      - rules/coalesce.md
      - rules/comparison_negation.md
      - rules/download_file.md
      - rules/duplicated_arguments.md
      - rules/equals_na.md
      - rules/expect_length.md
      - rules/expect_named.md
      - rules/expect_not.md
      - rules/expect_null.md
      - rules/expect_true_false.md
      - rules/for_loop_index.md
      - rules/grepv.md
      - rules/implicit_assignment.md
      - rules/is_numeric.md
      - rules/length_levels.md
      - rules/length_test.md
      - rules/lengths.md
      - rules/list2df.md
      - rules/matrix_apply.md
      - rules/numeric_leading_zero.md
      - rules/outer_negation.md
      - rules/redundant_equals.md
      - rules/repeat.md
      - rules/sample_int.md
      - rules/seq.md
      - rules/seq2.md
      - rules/sort.md
      - rules/system_file.md
      - rules/true_false_symbol.md
      - rules/which_grepl.md
