name: cargo-test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cargo-test.yml
      - Cargo.toml
      - dist-workspace.toml
      - crates/**/src/**
      - crates/**/tests/**
      - crates/**/Cargo.toml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/cargo-test.yml
      - Cargo.toml
      - dist-workspace.toml
      - crates/**/src/**
      - crates/**/tests/**
      - crates/**/Cargo.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: cargo-test
    strategy:
      matrix:
        toolchain: [stable, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - run: cargo install --path crates/jarl --profile=dev --force
      - run: cargo test --verbose
